# Matriks

## Tujuan Belajar:

Bagian dari aljbar linear yang membantu kita menyimpan matriks u=[1,3,5] - vektor dengan 3 elemen. Dalam DS vektor mrpk representasi dari data. Matriks tidak mempunyai informasi data per baris dan kolom.



### Terlongkap di INVERS, DETERMINAN, DAN TENSOR

## Mendefinisikan

In [1]:
## menggunakan numpy
import numpy as np

In [2]:
data_1 = [1,2,3] #array 1 Dimensi, di dalam array langsung data
data_2 = [[1,2,3],[4,5]] # array 2 dimensi, di dalam array ada array
                        # bukan matriks karena jumlah elemen array pertama dan array kedua berbeda
data_3 = [[1,2,3],[4,5,6]] #matriks


In [3]:
vec = np.array(data_1) #vektor
vec

array([1, 2, 3])

In [4]:
data =np.array (data_2)
data

C:\Users\WENNYC~1\AppData\Local\Temp/ipykernel_8200/3881169494.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data =np.array (data_2)


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [5]:
mat = np.array (data_3) #definisi matriks -- pastikan jumlah elemen di tiap list sama
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
mat = np.array (data_3)
print(mat)

[[1 2 3]
 [4 5 6]]


## Tipe-tipe Matriks

- square matrix
- upper triangle matrix
- lower triangle matrix
- diagonal matrix
- identity matrix

## Pertambahan/Pengurangan Matriks

In [7]:
A = [[1,2,3],
    [4,5,6],
    [7,8,9]]
A =np.array(A) #mengubah list menjadi matriks
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
B = [[7,8,9],
    [9,8,7],
    [6,5,4]]
B =np.array(B)
B

array([[7, 8, 9],
       [9, 8, 7],
       [6, 5, 4]])

In [9]:
print(np.array([[2,4],[1,8]]))

[[2 4]
 [1 8]]


In [10]:
A + B

array([[ 8, 10, 12],
       [13, 13, 13],
       [13, 13, 13]])

## Perkalian

In [11]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#perkalian dengan skalar
3*A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [13]:
B

array([[7, 8, 9],
       [9, 8, 7],
       [6, 5, 4]])

In [14]:
#perkalian Hadamart (element wise) -- bukan perkalian matriks
A * B

array([[ 7, 16, 27],
       [36, 40, 42],
       [42, 40, 36]])

In [15]:
#perkalian Matriks dan Matriks - Matrix to matrix multiplication

A @ B

array([[ 43,  39,  35],
       [109, 102,  95],
       [175, 165, 155]])

In [16]:
np.dot (A,B)

array([[ 43,  39,  35],
       [109, 102,  95],
       [175, 165, 155]])

In [18]:
# contoh lain, ordo matrix A 3x2 dan ordo matrix B adalah 2x3
A = [[1,2],
    [3,4],
    [5,6]]

A = np.array(A)

B = [[5,6,7],
    [8,9,3]]
    
B = np.array (B)

In [19]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
B

array([[5, 6, 7],
       [8, 9, 3]])

In [21]:
A @ B

array([[21, 24, 13],
       [47, 54, 33],
       [73, 84, 53]])

## Pembagian Matriks -- Hadamart

In [22]:
A = [[1,1,1],
    [2,2,2],
    [3,3,3]]
A =np.array(A) #mengubah list menjadi matriks
A

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [23]:
B = [[3,3,3],
    [2,2,2],
    [1,1,1]]
B =np.array(B)
B

array([[3, 3, 3],
       [2, 2, 2],
       [1, 1, 1]])

In [24]:
A/B #pembagian hadamart

array([[0.33333333, 0.33333333, 0.33333333],
       [1.        , 1.        , 1.        ],
       [3.        , 3.        , 3.        ]])

## Transpose -- membalikkan matriks

In [25]:
C = [[1,2], [3,4], [5,6]]
C = np.array (C)

In [26]:
C.T

array([[1, 3, 5],
       [2, 4, 6]])

In [27]:
D = C.T
D

array([[1, 3, 5],
       [2, 4, 6]])

## Invers

In [28]:
A = [[1,2],[7,8]]
A = np.array(A)
A

array([[1, 2],
       [7, 8]])

In [29]:
from numpy.linalg import inv #invers yang dikalikan menghasilkan identitas
inv_A = inv(A)
inv_A

array([[-1.33333333,  0.33333333],
       [ 1.16666667, -0.16666667]])

In [30]:
A @ inv_A #invers yang dikalikan menghasilkan identitas

array([[1., 0.],
       [0., 1.]])

In [31]:
inv_A @ A

array([[1., 0.],
       [0., 1.]])

In [32]:
0.1 + 0.2

0.30000000000000004

In [33]:
# tidak semua matriks memiliki invers, yaitu matriks yang determinannya 0/matrix singular: matrix yang merupakan kelipatan atau kombinasi linear dari baris baris yang lain

In [34]:
np.linalg.inv(A)

array([[-1.33333333,  0.33333333],
       [ 1.16666667, -0.16666667]])

array([[-1.33333333,  0.33333333],
       [ 1.16666667, -0.16666667]])

## Determinan

In [38]:
#untuk menentukan apakah matrix mempunyai invers, Det = 0, matriks singular -- tidak mempunyai invers; matrix yang ada Det -- bisa dicari inversnya
#matriks bentuk persegi
from numpy.linalg import det
F = np.array([[1,2],[2,4]])
det(F)

0.0

In [39]:
from numpy.linalg import det
B = np.array([[1,2,3], [2,5,7], [3,7,3]])
det(B)

-7.000000000000001

In [40]:
inv(B)

array([[ 4.85714286, -2.14285714,  0.14285714],
       [-2.14285714,  0.85714286,  0.14285714],
       [ 0.14285714,  0.14285714, -0.14285714]])

## Tensor -- Matrix yang ditaruh di dalam List

In [ ]:
# Array 3 D

In [38]:
A = np.array([[1,2], [7,8], [1,1], [1,1]])
B = np.array([[1,1], [1,1], [1,1], [1,1]])
C = np.array([[1,1], [1,1], [1,1], [1,1]])

In [39]:
A.shape

(4, 2)

In [40]:
tensor = [A, B, C]
tensor = np.array(tensor)
tensor

array([[[1, 2],
        [7, 8],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [41]:
tensor.shape

(3, 4, 2)