In [2]:
import numpy as np

## 1. Membuat Tensor

In [4]:

A = np.array([[23,50],[7,12]])
B = np.array([[57,67],[99,43]])
C = np.array([[75,21],[57,12]])
D = np.array([[87,26],[18,84]])

In [8]:
tensor = [A,B,C,D]
tensor = np.array(tensor)
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

## 2. Perkalian Matrix

In [9]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([17,22,19])

In [10]:
A @ B

array([1852, 2454, 4305])

In [11]:
A * B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

## 3. Transpose, Determinant, dan Invers

In [12]:
A = np.array ([[23,50,19],[7,12,109],[57,67,98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [21]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [22]:
from numpy.linalg import det
det(A)

131344.0000000002

In [23]:
from numpy.linalg import inv
inv_A = inv(A)
inv_A

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])