In [4]:
a = [17, 22, 19]

In [5]:
import numpy as np

## Soal nomor 1

In [8]:
ve_a = np.array (a)
ve_a

array([17, 22, 19])

## Soal nomor 2

In [14]:
b = [10, 20, 11]
c = [5, 12, 9]

ve_b = np.array (b)
ve_c = np.array (c)

print('Vector A: ', ve_a)
print('Vector B: ', ve_b)
print('Vector C: ', ve_c)


Vector A:  [17 22 19]
Vector B:  [10 20 11]
Vector C:  [ 5 12  9]


In [12]:
ve_a + ve_b

array([27, 42, 30])

In [13]:
ve_b - ve_c

array([5, 8, 2])

In [16]:
print( ve_a.dot(ve_b))


819


In [17]:
ve_a * ve_b

array([170, 440, 209])

In [18]:
np.linalg.norm(ve_a)


33.67491648096547

In [22]:
result_dot_product = ve_a.dot(ve_b)
cos_theta = result_dot_product / (np.linalg.norm(ve_a)*np.linalg.norm(ve_b))

print(cos_theta)

0.9759590023331435
