In [ ]:
#untuk install numpy
#pip install numpy di Terminal

In [6]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(2)

array([1., 1.])

In [9]:
np.empty(2)

array([1., 1.])

In [13]:
print(np.arange(2,11,3))
print(np.arange(2))

[2 5 8]
[0 1]


In [14]:
#list error
height= [1.73, 1.68, 1.71, 1.86, 1.87]
weight= [65.4, 59.2, 63.2, 88.4, 68.7]

weight/height **2 

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [15]:
#list ubah jadi numpy untuk perhitungan
height= [1.73, 1.68, 1.71, 1.86, 1.87]
weight= [65.4, 59.2, 63.2, 88.4, 68.7]

np_height= np.array(height)
np_weight= np.array(weight)

np_weight/np_height **2  

array([21.85171573, 20.97505669, 21.61348791, 25.55208695, 19.64597215])

In [16]:
#list ubah jadi numpy untuk perhitungan
height= np.array ([1.73, 1.68, 1.71, 1.86, 1.87])
weight= np.array ([65.4, 59.2, 63.2, 88.4, 68.7])
np_weight/np_height **2  

array([21.85171573, 20.97505669, 21.61348791, 25.55208695, 19.64597215])

In [17]:
arr= np.array ([1,2,3,4,5])
np.append(arr,[6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
#lihat external reference juga

In [22]:
#Latihan
Import numpy as np
x = np.arrange (2,11).reshape (3.3)
print (x)
print (x.shape)
print (x.ndim)
#2 dimensi

SyntaxError: invalid syntax (Temp/ipykernel_3496/194605309.py, line 2)

In [23]:
arr = np.array (70)
print(arr)
#0 dimensi

70


In [25]:
arr = np.array ([[1,2,3],[4,5,6],[4,5,6]])
print (arr)
arr.shape

[[1 2 3]
 [4 5 6]
 [4 5 6]]


(3, 3)

In [28]:
arr = np.array ([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
arr.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(2, 2, 3)

In [32]:
array_tes = np.array ([[3,7,10,2],[3,7,10,2]], ndmin=4)
print(array_tes)

[[[[ 3  7 10  2]
   [ 3  7 10  2]]]]


In [33]:
import numpy as np
array_tes =np.array ([3,10,3,2])

print(array_tes[3]+array_tes[2])

#pertambahan indeks

5


In [34]:
arr=np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[1,3])
#indeks ke 1 yaitu [1,2,3,4,5] kemudian indeks ke 3 == dibuka perkurung

4


In [39]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[:,1,2])
print(arr.shape)

# : ambil keseluruhan -- : melambangkan range urutan mulai dari 1 dan terus ditambah 2 (mencakup 1 dan 2)
# 1,2 adalah indeks urutan mulai dari 0

[ 6 12]
(2, 2, 3)


In [46]:
print(arr[:1,1,1])


[5]


In [49]:
print(arr[:2,1,1])
# : melambangkan range urutan mulai dari 1 dan terus ditambah 2 (mencakup 1 dan 2)
# 1,2 adalah indeks urutan mulai dari 0

[ 5 11]


In [50]:
print(arr[:1,:2,1])

[[2 5]]


In [51]:
print(arr[:1,:2,:1]) #termasuk kurung

[[[1]
  [4]]]


In [54]:
arr=np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[-1,-1])

9


In [55]:
arr=np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[-2,-2])

9


In [56]:
arr = np.array([4,5,6,7,1,2,3])
print(arr[1:6:4])

[5 2]


In [57]:
arr = np.array([4,5,6,7,1,2,3])
print(arr[1:5:4])

[5]


In [58]:
arr = np.array([2,2,7,4,5,6,7,8,10])
print (arr[2:8:3]) #start end step
print (arr[::3]) #start end step 

[7 6]
[2 4 7]


In [59]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [60]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,-1) #unknown dimension
print(newarr, "\n")
print(newarr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

(2, 2, 3)


In [61]:
def convert(fahr):
    cels = fahr * 1.8 +32.0
    return cels
print(convert(32))

89.6


In [64]:
def convert(fahr,kelv):
    cels=fahr * 1.8 + 32.0
    cels2=kelv-273,15
    return cels, cels2
print("Temperature in celcius (C) =", convert (32,20))

Temperature in celcius (C) = (89.6, (-253, 15))
