# Pandas

## Intro

2 tipe data pada Pandas: Series & Data Frame

Series - 1 kolom
Data Frame - Baris dan Kolom

Series digabungkan menjadi Data Frame

Data yang sudah dipelajari sebelumnya: Integer, Float, String, Tuple, List, Dictionary, Numpy, Array

Data yang dipelajari hari ini: Series, Data Frame

Tools: Jupyter Notebook Lokal, Visual Studio Code, Google Collab

## Installing Pandas

! untuk menjalankan terminal di dalam cell
Install
(terminal)  pip install pandas
            conda install pandas
(cell notebook) !pip install pandas

## Running Pandas

In [3]:
import numpy as np
import pandas as pd

## Data Structure: Series

In [4]:
pd.Series ([1200,2000,3000,4000])

#Series huruf besar
#Int64 int tipe data 
#64 Bit precision - sbrp banyak memori kalian bisa menyimpan data 64 Bit, 32 Bit
#coba list integer, string, float, dll

0    1200
1    2000
2    3000
3    4000
dtype: int64

In [5]:
pd.Series (['merah','jingga','kuning','hijau'])

0     merah
1    jingga
2    kuning
3     hijau
dtype: object

In [6]:
pd.Series ([1200.,2000.,3000.,4000.])

0    1200.0
1    2000.0
2    3000.0
3    4000.0
dtype: float64

In [7]:
pd.Series ([1200,2000.,'3000',4000])
#bentuk data macam2 tipe data objek
#artinya harus diperbaiki semampunya
#memori lebih kecil kalau diperbaiki drpd tipe data objek

0      1200
1    2000.0
2      3000
3      4000
dtype: object

In [8]:
revenues = pd.Series([5555, 7000, 1980])

In [9]:
revenues
# index [0,1,2] - sequence of values [5555, 7000, 1980]
# index dimulai dari 0 kalau kita tidak memasukkan indeks


0    5555
1    7000
2    1980
dtype: int64

In [10]:
revenues.values

# function .notation
# .values = list of values
# array = himpunan


array([5555, 7000, 1980], dtype=int64)

In [11]:
revenues.index

RangeIndex(start=0, stop=3, step=1)

In [12]:
pd.Series ([10,20,30,40,50], index=['A','B','C','D', 'E'])
#series dan indeks
#membuat series atau pd.series dengan list

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [13]:
city_revenues = pd.Series(
    [4200, 8000, 6500],
    index=["Amsterdam", "Toronto", "Tokyo"]
)


In [14]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [15]:
city_employee_count = pd.Series({"Amsterdam": 5, "Tokyo": 8})
#membuat pd.Series dengan Dictionary

In [16]:
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

In [17]:
pd.Series({'Amsterdam':10, 'Jakarta':20, 'Magetan': 50})

Amsterdam    10
Jakarta      20
Magetan      50
dtype: int64

In [18]:
#memanggil values
city_employee_count.values

array([5, 8], dtype=int64)

In [19]:
#memanggil indeks
city_employee_count.index

Index(['Amsterdam', 'Tokyo'], dtype='object')

In [20]:
city_employee_count.keys()

Index(['Amsterdam', 'Tokyo'], dtype='object')

In [21]:
#in untuk cara mencari data index
"Tokyo" in city_employee_count

True

In [22]:
"New York" in city_employee_count


False

In [23]:
pd.DataFrame({
    'nama kolom': value,
    'nama kolom kedua': value
})

NameError: name 'value' is not defined

In [ ]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [ ]:
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

In [ ]:
city_data = pd.DataFrame({
    "revenue": city_revenues,
    "employee_count": city_employee_count
})

In [ ]:
city_data
#Indeks tergabung
# NaN - not a number

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [ ]:
city_data.index

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [ ]:
city_data.values

#4.2e+3 = 4.2 x 10^3
#4.2e-3 = 4.2 x 10^-3


array([[4.2e+03, 5.0e+00],
       [6.5e+03, 8.0e+00],
       [8.0e+03,     nan]])

In [ ]:
#belajar axis 0 menurun indeks
# axis 1 menyamping - kolom
city_data.axes[0]

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [ ]:
city_data.axes[1]

Index(['revenue', 'employee_count'], dtype='object')

In [ ]:
city_data.keys()

Index(['revenue', 'employee_count'], dtype='object')

In [ ]:
city_data.columns

Index(['revenue', 'employee_count'], dtype='object')

In [ ]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [ ]:
'Amsterdam' in city_data
'Tokyo' in city_data

False

In [ ]:
'revenue' in city_data

#in pada Series merujuk indeks
#in pada DataFrame merujuk kolom: revenue dan employee_count

True

## Accessing Series Elements

In [ ]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [ ]:
city_revenues ['Tokyo']
#dengan merujuk ke indeks atau label (indeks yang bukan angka)

6500

In [ ]:
city_revenues [1]

8000

In [ ]:
city_revenues [-1]

6500

In [ ]:
city_revenues [1:]

Toronto    8000
Tokyo      6500
dtype: int64

In [ ]:
city_revenues ["Toronto":]

Toronto    8000
Tokyo      6500
dtype: int64

## .iloc and .loc

In [ ]:
#loc berdasarkan label indeks
#iloc berdasarkan indeks

In [ ]:
colors = pd.Series(
    ["red", "purple", "blue", "green", "yellow"],
    index=[1, 2, 3, 5, 8]
)

In [ ]:
colors

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

In [ ]:
colors.loc[1]
#berdasarkan label

'red'

In [ ]:
colors.iloc[1]
#berdasarkan indeks

## Accessing DataFrame Elements

In [ ]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [ ]:
city_data ["revenue"]

Amsterdam    4200
Tokyo        6500
Toronto      8000
Name: revenue, dtype: int64

In [ ]:
city_data ["employee_count"]

Amsterdam    5.0
Tokyo        8.0
Toronto      NaN
Name: employee_count, dtype: float64

In [ ]:
city_data.revenue
#dengan notasi lebih cepat
#namun kalau kolomnya sama dengan keyword python

Amsterdam    4200
Tokyo        6500
Toronto      8000
Name: revenue, dtype: int64

In [ ]:
city_data.employee_count

Amsterdam    5.0
Tokyo        8.0
Toronto      NaN
Name: employee_count, dtype: float64

## .iloc and .loc

In [ ]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [ ]:
city_data.loc["Amsterdam"]

revenue           4200.0
employee_count       5.0
Name: Amsterdam, dtype: float64

In [ ]:
city_data.loc["Tokyo": "Toronto"]

revenue  employee_count
Tokyo       6500             8.0
Toronto     8000             NaN

## Combining Multiple Datasets

In [ ]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [ ]:
further_city_data = pd.DataFrame(
    {"revenue": [7000, 3400], "employee_count": [2, 2]},
    index=["New York", "Barcelona"]
)

In [ ]:
further_city_data

revenue  employee_count
New York      7000               2
Barcelona     3400               2

In [ ]:
pd.concat([data_pertama, data_kedua])

In [ ]:
all_city_data = pd.concat([city_data, further_city_data], sort=False)
#sort urutan; untuk data yang banyak, sort dianjurkan false atau tidak disort makan waktu lama

In [ ]:
all_city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN
New York      7000             2.0
Barcelona     3400             2.0

In [ ]:
city_countries = pd.DataFrame({
    "country": ["Holland", "Japan", "Holland", "Canada", "Spain"],
    "capital": [1, 1, 0, 0, 0]},
    index=["Amsterdam", "Tokyo", "Rotterdam", "Toronto", "Barcelona"])

In [ ]:
city_countries

country  capital
Amsterdam  Holland        1
Tokyo        Japan        1
Rotterdam  Holland        0
Toronto     Canada        0
Barcelona    Spain        0

In [ ]:
cities = pd.concat ([all_city_data, city_countries], axis = 1, sort = False)
#axis = 1 ke samping


In [ ]:
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             5.0  Holland      1.0
Tokyo       6500.0             8.0    Japan      1.0
Toronto     8000.0             NaN   Canada      0.0
New York    7000.0             2.0      NaN      NaN
Barcelona   3400.0             2.0    Spain      0.0
Rotterdam      NaN             NaN  Holland      0.0

In [ ]:
cities = pd.concat ([all_city_data, city_countries], axis = 1, join='inner')
#data yang tidak ada di kedua tabel tidak dimasukkan

In [ ]:
cities

revenue  employee_count  country  capital
Amsterdam     4200             5.0  Holland        1
Tokyo         6500             8.0    Japan        1
Toronto       8000             NaN   Canada        0
Barcelona     3400             2.0    Spain        0

In [ ]:
cities = pd.concat ([all_city_data, city_countries], axis = 1, join='outer')
#sama seperti concat biasa, semua data digabung

In [ ]:
cities

revenue  employee_count  country  capital
Amsterdam   4200.0             5.0  Holland      1.0
Tokyo       6500.0             8.0    Japan      1.0
Toronto     8000.0             NaN   Canada      0.0
New York    7000.0             2.0      NaN      NaN
Barcelona   3400.0             2.0    Spain      0.0
Rotterdam      NaN             NaN  Holland      0.0

In [ ]:
countries = pd.DataFrame({
    "population_millions": [17, 127, 37],
    "continent": ["Europe", "Asia", "North America"]
}, index=["Holland", "Japan", "Canada"])

In [ ]:
countries

population_millions      continent
Holland                   17         Europe
Japan                    127           Asia
Canada                    37  North America

In [ ]:
pd.merge(cities, countries, left_on="country", right_index=True)
#left_on = karena yang jadi acuan penggabungan adalah kolom yang berada di tabel sebelah kiri (tabel cities)
#right_index = karena yang digabungkan yang ada di index kanan, yang diindex kanan tidak ada atau Nan tidak ikut digabungkan.
#right_index = yang Barcelona dan New York dihilangkan.

revenue  employee_count  country  capital  population_millions  \
Amsterdam   4200.0             5.0  Holland      1.0                   17   
Rotterdam      NaN             NaN  Holland      0.0                   17   
Tokyo       6500.0             8.0    Japan      1.0                  127   
Toronto     8000.0             NaN   Canada      0.0                   37   

               continent  
Amsterdam         Europe  
Rotterdam         Europe  
Tokyo               Asia  
Toronto    North America

In [ ]:
pd.merge(
    cities,
    countries,
    left_on="country",
    right_index=True,
    how="left"
)

#how semua index di left dipakai, yang kosong NaN

revenue  employee_count  country  capital  population_millions  \
Amsterdam   4200.0             5.0  Holland      1.0                 17.0   
Tokyo       6500.0             8.0    Japan      1.0                127.0   
Toronto     8000.0             NaN   Canada      0.0                 37.0   
New York    7000.0             2.0      NaN      NaN                  NaN   
Barcelona   3400.0             2.0    Spain      0.0                  NaN   
Rotterdam      NaN             NaN  Holland      0.0                 17.0   

               continent  
Amsterdam         Europe  
Tokyo               Asia  
Toronto    North America  
New York             NaN  
Barcelona            NaN  
Rotterdam         Europe