# Pandas

## Intro

2 tipe data pada Pandas: Series & Data Frame

Series - 1 kolom
Data Frame - Baris dan Kolom

Series digabungkan menjadi Data Frame

Data yang sudah dipelajari sebelumnya: Integer, Float, String, Tuple, List, Dictionary, Numpy, Array

Data yang dipelajari hari ini: Series, Data Frame

Tools: Jupyter Notebook Lokal, Visual Studio Code, Google Collab

## Installing Pandas

! untuk menjalankan terminal di dalam cell
Install
(terminal)  pip install pandas
            conda install pandas
(cell notebook) !pip install pandas

## Running Pandas

In [5]:
import numpy as np
import pandas as pd

## Data Structure: Series

In [3]:
pd.Series ([1200,2000,3000,4000])

#Series huruf besar
#Int64 int tipe data 
#64 Bit precision - sbrp banyak memori kalian bisa menyimpan data 64 Bit, 32 Bit
#coba list integer, string, float, dll

0    1200
1    2000
2    3000
3    4000
dtype: int64

In [6]:
pd.Series (['merah','jingga','kuning','hijau'])

#????????????tipe data objek???????????bukan string

0     merah
1    jingga
2    kuning
3     hijau
dtype: object

In [8]:
pd.Series ([1200.,2000.,3000.,4000.])

0    1200.0
1    2000.0
2    3000.0
3    4000.0
4       500
dtype: object

In [5]:
pd.Series ([1200,2000.,'3000',4000])
#bentuk data macam2 tipe data objek
#artinya harus diperbaiki semampunya
#memori lebih kecil kalau diperbaiki drpd tipe data objek

0      1200
1    2000.0
2      3000
3      4000
dtype: object

In [6]:
revenues = pd.Series([5555, 7000, 1980])

In [7]:
revenues
# index [0,1,2] - sequence of values [5555, 7000, 1980]
# index dimulai dari 0 kalau kita tidak memasukkan indeks


0    5555
1    7000
2    1980
dtype: int64

In [8]:
revenues.values

# function .notation
# .values = list of values
# array = himpunan


array([5555, 7000, 1980], dtype=int64)

In [9]:
revenues.index

RangeIndex(start=0, stop=3, step=1)

In [11]:
#series dan indeks
pd.Series ([10,20,30,40,50], index=['A','B','C','D', 'E'])

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [12]:
city_revenues = pd.Series(
    [4200, 8000, 6500],
    index=["Amsterdam", "Toronto", "Tokyo"]
)


In [13]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [14]:
city_employee_count = pd.Series({"Amsterdam": 5, "Tokyo": 8})


In [15]:
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

In [17]:
pd.Series({'Amsterdam':10, 'Jakarta':20, 'Magetan': 50})

Amsterdam    10
Jakarta      20
Magetan      50
dtype: int64

In [18]:
#memanggil values
city_employee_count.values

array([5, 8], dtype=int64)

In [19]:
#memanggil indeks
city_employee_count.index

Index(['Amsterdam', 'Tokyo'], dtype='object')

In [23]:
city_employee_count.keys()

Index(['Amsterdam', 'Tokyo'], dtype='object')

In [21]:
#cara mencari data
"Tokyo" in city_employee_count

True

In [22]:
"New York" in city_employee_count


False

In [28]:
pd.DataFrame({
    'nama kolom': value,
    'nama kolom kedua': value
})

NameError: name 'value' is not defined

In [26]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [36]:
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

In [30]:
city_data = pd.DataFrame({
    "revenue": city_revenues,
    "employee_count": city_employee_count
})

In [31]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [32]:
city_data.index

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [33]:
city_data.values

#4.2e+3 = 4.2 x 10^3
#4.2e-3 = 4.2 x 10^-3


array([[4.2e+03, 5.0e+00],
       [6.5e+03, 8.0e+00],
       [8.0e+03,     nan]])

In [34]:
#belajar axis 0 - indeks
city_data.axes[0]

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [35]:
city_data.axes[1]

Index(['revenue', 'employee_count'], dtype='object')

In [37]:
city_data.keys()

Index(['revenue', 'employee_count'], dtype='object')

In [38]:
city_data.columns

Index(['revenue', 'employee_count'], dtype='object')

In [40]:
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

In [41]:
city_data.axes

[Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object'),
 Index(['revenue', 'employee_count'], dtype='object')]

In [42]:
city_data.loc["Tokyo": "Toronto"]

revenue  employee_count
Tokyo       6500             8.0
Toronto     8000             NaN

In [ ]:
further_city_data = pd.DataFrame(
    {"revenue": [7000, 3400], "employee_count": [2, 2]},
    index=["New York", "Barcelona"]

#Combining Multiple Datasets

In [46]:
city_countries = pd.DataFrame({
    "country": ["Holland", "Japan", "Holland", "Canada", "Spain"],
    "capital": [1, 1, 0, 0, 0]},
    index=["Amsterdam", "Tokyo", "Rotterdam", "Toronto", "Barcelona"])

In [47]:
city_countries

country  capital
Amsterdam  Holland        1
Tokyo        Japan        1
Rotterdam  Holland        0
Toronto     Canada        0
Barcelona    Spain        0